---
- vars:
    playbook_name: setup-stg
  name: "{{ playbook_dir }}/{{ playbook_name }}"
  hosts: all
  tasks:
    - name: "Check hostname"
      shell:
        hostname
      register: host_info
    - debug:
        msg: "{{host_info.stdout_lines}}"