name: 'Ansible Config STG'
on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: environment   
          required: true
          default: stg

jobs:

  playbook-dev:
    name: 'Ansible Install'
    runs-on: ubuntu-20.04
    environment: stg
    container: gcr.io/google.com/cloudsdktool/cloud-sdk:286.0.0-alpine
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
      ANSIBLE_BECOME: "True"
      OS_LOGIN_SSH_TTL: "1h"
      ANSIBLE_REMOTE_USER: to-be-calculated-during-job

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: List
      run: ls -al

    - name: Set up Ansible & SSH
      run: |
        apk add ansible --update
        gcloud auth activate-service-account --key-file=account.json --project=kubernetes-istio-gcp
        pip3 install requests google-auth
        apk add jq --update
        export ANSIBLE_REMOTE_USER="sa_$(cat account.json | jq -r '.client_id')"
        export ANSIBLE_HOST_KEY_CHECKING=False
        ansible-playbook -v -i ./ansible/inventory/stg-gcp.yaml  ./ansible/playbooks/*.yaml
      env:
        STG_PRIVATE_KEY: ${{ secrets.CREDENTIALS_VM }}
        FTP_SERVER_KEY: ${{ secrets.FTP_SERVER_KEY_STG }}